Repository Rikj000/MoniGoMani, pull requests merged in 2021-06, with the labels that each got.

#31 changed broken links of custom hyperopt scripts.
  MGM_DOCUMENTATION.md
Labels: Documentation

#30 custom stoploss search space with configurable parameter max value
  user_data/strategies/MoniGoManiHyperStrategy.py
Labels: Feature - New

#58 Small updates on README.md
  README.md
Labels: Documentation, In Progress

#61 Cleanup temporary/changing data from user_data/
  .gitignore
Labels: Feature - Enhancement, In Progress

#71 Merge Conflicting Trailing documentation commits
  README.md
Labels: Bug - Fixed, Documentation

#72 Fixes broken link
  MGM_DOCUMENTATION.md
Labels: Documentation
