Repository Rikj000/MoniGoMani, pull requests merged in 2021-07, with the labels that each got.

#79 Improve new trend detection hilbert transform by using SAR
  MGM_DOCUMENTATION.md
  user_data/strategies/MasterMoniGoManiHyperStrategy.py
  user_data/strategies/MoniGoManiHyperStrategy.py
Labels: Feature - Enhancement, In Progress

#82 Feature/issue 81
  user_data/mgm-config.example.json
  user_data/strategies/MasterMoniGoManiHyperStrategy.py
Labels: Feature - Enhancement, In Progress, Needs Testing

#92 fix(hyperopt): fail gracefully on bad hyperopt json
  user_data/strategies/MasterMoniGoManiHyperStrategy.py
Labels: Feature - Enhancement

#86 feat(mgm-tools): kraken support in data downloader script, parallelism support
  user_data/mgm_tools/Freqtrade-Download-Pairs.sh
Labels: Feature - New

#93 Feature/mgm hurry
  .github/workflows/pylint-analysis.yml
  .hurry
  README.md
  TODO.md
  mgm-hurry
  requirements.txt
  user_data/mgm_tools/mgm_hurry/.pylintrc
  user_data/mgm_tools/mgm_hurry/FreqtradeCli.py
  user_data/mgm_tools/mgm_hurry/LeetLogger.py
  user_data/mgm_tools/mgm_hurry/MgmCli.py
  user_data/mgm_tools/mgm_hurry/README.md
  user_data/mgm_tools/mgm_hurry/__pycache__/FreqtradeCli.cpython-39.pyc
  user_data/mgm_tools/mgm_hurry/__pycache__/LeetLogger.cpython-39.pyc
  user_data/mgm_tools/mgm_hurry/__pycache__/MgmCli.cpython-39.pyc
Labels: Feature - New, Planned

#96 Fixes unit-test (bug)
  tests/test_mgm_hurry_monigomani_cli.py
Labels: Bug - Fixed
