Repository Rikj000/MoniGoMani, pull requests merged in 2021-09, with the labels that each got.

#124 installer - Adding a requirement check for python3-venv
  installer.sh
Labels: Feature - Enhancement

#143 ⚡️ Allow `mgm-hurry hyperopt_show_epoch --fthypt` to use a `fthypt_name`
  mgm-hurry
Labels: Feature - Enhancement

#146 🐞 BugFix: Get docker running
  docker/Dockerfile.MoniGoMani
Labels: Bug - Fixed, Feature - Enhancement

#140 ✨ New indicators + minor roi,lookback candles adjustment.
  user_data/mgm-config.example.json
  user_data/strategies/MoniGoManiHyperStrategy.py
Labels: Feature - Enhancement, Feature - New
