Repository Rikj000/MoniGoMani, pull requests merged in 2022-01, with the labels that each got.

#228 ✨ Added `mgm-hurry export_results` - Package up test results for easy share-ability
  Documentation/Docs-MGM-Hurry.md
  mgm-hurry
  user_data/mgm_result_export/.gitkeep
  user_data/mgm_tools/mgm_hurry/MoniGoManiLogger.py
Labels: Feature - New

#229 🐞 BugFix - Change `rawlist` to `list` in `export_results`
  mgm-hurry
Labels: Bug - Fixed

#232 ⚡️ Add `strategy` and `loss` files to results export.
  mgm-hurry
  user_data/mgm_tools/mgm_hurry/MoniGoManiCli.py
Labels: Feature - Enhancement

#234 ✨ Added `SparkyLinux` support
  user_data/mgm_tools/mgm_hurry/FreqtradeCli.py
Labels: Bug - Fixed

#245 ✨ Export trades from hyperopt/backtest result
  user_data/mgm_tools/ExportCsvBacktest.py
  user_data/mgm_tools/ExportCsvTrades.py
Labels: Feature - New, Planned, Needs Testing
